config/routes.rb
Rails.application.routes.draw do

  # Set up staging URLs
  if Rails.env.staging?
    constraints :subdomain => "api.staging" do
      scope :module => "api", :as => "api" do
        get 'menus', to: 'menus#index'
        get 'photos', to: 'photos#index'
        get 'press', to: 'press#index'
        get 'pages', to: 'pages#index'
        get 'employees', to: 'employees#index'
      end
    end
    constraints :subdomain => "admin.staging" do
        #ActiveAdmin.routes(self)
        ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
        devise_for :admin_users, ActiveAdmin::Devise.config
    end
  # Set up production subdomains
  elsif Rails.env.production? || Rails.env.development?
    constraints :subdomain => "api" do
      scope :module => "api", :as => "api" do
        get 'menus', to: 'menus#index'
        get 'photos', to: 'photos#index'
        get 'press', to: 'press#index'
        get 'pages', to: 'pages#index'
        get 'employees', to: 'employees#index'
      end
    end
    constraints :subdomain => "admin" do
        #ActiveAdmin.routes(self)
        ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
        devise_for :admin_users, ActiveAdmin::Devise.config
    end
  end


  # You can have the root of your site routed with "root"
  #root 'home#index'

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/dish.rb
class Dish < ActiveRecord::Base
  belongs_to :meal
  validates :title, presence: true
  acts_as_list scope: :meal
  #default_scope {:order => 'dishes.position'}
end

app/models/employee.rb
class Employee < ActiveRecord::Base

  default_scope { order(position: :asc) }
  acts_as_list
  dragonfly_accessor :image
  validates_size_of :image, maximum: 500.kilobytes,
    message: "should be no more than 500 KB", if: :image_changed?
  validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
    message: "should be either .jpeg, .jpg, .png, .bmp", if: :image_changed?
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :photos
  accepts_nested_attributes_for :photos
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :menu
  accepts_nested_attributes_for :menu
  has_many :dishes, ->{ order(:position)}
  acts_as_list scope: :menu
  validates :title, presence: true
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  has_many :meals, ->{ order(:position)}
  validates :title, presence: true
end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :title, presence: true
  before_save      Page.new

  def before_save(page)
    Rails::logger.info
    page.body = ActionController::Base.helpers.sanitize(page.body)
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :gallery
  accepts_nested_attributes_for :gallery
  default_scope { order(position: :asc) }
  acts_as_list
  dragonfly_accessor :image
  validates :image, presence: true
  validates_size_of :image, maximum: 2.megabytes,
    message: "should be no more than 500 KB", if: :image_changed?
  validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
    message: "should be either .jpeg, .jpg, .png, .bmp", if: :image_changed?
end

app/models/press.rb
class Press < ActiveRecord::Base

  default_scope { order(position: :asc) }
  acts_as_list
  dragonfly_accessor :image
  validates_size_of :image, maximum: 500.kilobytes,
    message: "should be no more than 500 KB", if: :image_changed?
  validates_property :format, of: :image, in: [:jpeg, :jpg, :png, :bmp], case_sensitive: false,
    message: "should be either .jpeg, .jpg, .png, .bmp", if: :image_changed?
end

app/controllers/api/menus_controller.rb
class Api::MenusController < ApplicationController

  def new
  end

  def create
    @menu = Menu.new(menu_params)

    @menu.save
    redirect_to @menu
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def index
      @menus = Menu.all
  end

  private
    def menu_params
      params.required(:menu).permit(:title,:description)
    end

end

app/controllers/api/pages_controller.rb
class PageController < ApplicationController

  def new
    @page = Page.order('created_at DESC')
    @page = Page.new
  end

  def create
    respond_to do |format|
      @page = page.all
      @page = page.new(page_params)
      @page.save
    end
  end

  def index
    @page = page.all
  end

  def page_params
    params.require(:page).permit(:title, :body)
  end
end

app/controllers/api/photos_controller.rb
class Api::PhotosController < ApplicationController
  def new
    @photos = Photo.order('created_at DESC')
    @galleries = Gallery.all
    @photo = Photo.new
  end
 
  def create
    respond_to do |format|
      @photos = Photo.all
      @photo = Photo.new(photo_params)
      @photo.save
      format.html {redirect_to(:action => :index, :notice => 'Photo successfully created')}
      format.js {}
    end
  end

  def new_multiple
    @galleries = Gallery.all
    @photos = Photo.order('created_at DESC')
    @photo = Photo.new
  end

  def index
    @photos = Photo.all
  end
 
  private
 
  def photo_params
    params.require(:photo).permit(:image, :caption, :gallery_id)
  end
end

app/controllers/api/press_controller.rb
class Api::PressController < ApplicationController

  def new
    @press = Press.order('created_at DESC')
    @press = Press.new
  end

  def create
    respond_to do |format|
      @press = Press.all
      @press = Press.new(press_params)
      @press.save
    end
  end

  def index
    @press = Press.all
  end

  def press_params
    params.require(:press).permit(:title, :description, :image, :release_date, :embed_code, :url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/press_helper.rb
module PressHelper
end

app/views/admin/photos/_form.html.haml
#dropzone.fade
  Drop files here

= form_for @photo do |f|

  .form-group
    = f.label :image, "Or choose images here"
    = f.file_field :image, required: true, multiple: true, name: 'photo[image]'
    
  .progress-wrapper
    %p
      Bitrate:
      %span.bitrate
    .progress
      .progress-bar{:role => "progressbar"}
        0%

:javascript
  $(document).ready(function() {
    var multiple_photos_form = $('#new_photo');
    var wrapper = multiple_photos_form.find('.progress-wrapper');
    var progress_bar = wrapper.find('.progress-bar');
    var bitrate = wrapper.find('.bitrate');

    multiple_photos_form.fileupload({
      dataType: 'script',
      dropZone: $('#dropzone'), 
      add: function(e, data){
        types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
        file = data.files[0];
        if (types.test(file.type) || types.test(file.name)) {
          data.submit();
        } else {
          alert(file.name + " must be GIF, JPEG, BMP or PNG file");
        }
      }
    });
 
    multiple_photos_form.on('fileuploadsubmit', function (e, data) {
      data.formData = {
        'photo[caption]': $('#photo_caption').val(),
        'photo[gallery_id]': $('#photo_gallery_id').val()
      };
    });

    multiple_photos_form.on('fileuploadstart', function() {
      wrapper.show();
    });
     
    multiple_photos_form.on('fileuploaddone', function() {
      wrapper.hide();
      progress_bar.width(0); // Revert progress bar's width back to 0 for future uploads
    });
     
    multiple_photos_form.on('fileuploadprogressall', function (e, data) {
      bitrate.text((data.bitrate / 1024).toFixed(2) + 'Kb/s');
      var progress = parseInt(data.loaded / data.total * 100, 10);
      progress_bar.css('width', progress + '%').text(progress + '%');
    });

    $(document).bind('dragover', function (e) {
      var dropZone = $('#dropzone'),
              timeout = window.dropZoneTimeout;
      if (!timeout) {
        dropZone.addClass('in');
      } else {
        clearTimeout(timeout);
      }
      var found = false,
              node = e.target;
      do {
        if (node === dropZone[0]) {
          found = true;
          break;
        }
        node = node.parentNode;
      } while (node != null);
      if (found) {
        dropZone.addClass('hover');
      } else {
        dropZone.removeClass('hover');
      }
      window.dropZoneTimeout = setTimeout(function () {
        window.dropZoneTimeout = null;
        dropZone.removeClass('in hover');
      }, 100);
    });
  });

app/views/menus/~index.html.haml
%h1 Menus

= @menus.each do |menu|
  %p
    = link_to menu.title, menu_path(menu.id)

app/views/photos/_form.html.haml
#dropzone.fade
  Drop files here

= form_for @photo do |f|

  .form-group
    = f.label :image, "Or choose images here"
    = f.file_field :image, required: true, multiple: true, name: 'photo[image]'
    
  .progress-wrapper
    %p
      Bitrate:
      %span.bitrate
    .progress
      .progress-bar{:role => "progressbar"}
        0%

:javascript
  $(document).ready(function() {
    var multiple_photos_form = $('#new_photo');
    var wrapper = multiple_photos_form.find('.progress-wrapper');
    var progress_bar = wrapper.find('.progress-bar');
    var bitrate = wrapper.find('.bitrate');

    multiple_photos_form.fileupload({
      dataType: 'script',
      dropZone: $('#dropzone'), 
      add: function(e, data){
        types = /(\.|\/)(gif|jpe?g|png|bmp)$/i;
        file = data.files[0];
        if (types.test(file.type) || types.test(file.name)) {
          data.submit();
        } else {
          alert(file.name + " must be GIF, JPEG, BMP or PNG file");
        }
      }
    });
 
    multiple_photos_form.on('fileuploadsubmit', function (e, data) {
      data.formData = {
        'photo[caption]': $('#photo_caption').val(),
        'photo[gallery_id]': $('#photo_gallery_id').val()
      };
    });

    multiple_photos_form.on('fileuploadstart', function() {
      wrapper.show();
    });
     
    multiple_photos_form.on('fileuploaddone', function() {
      wrapper.hide();
      progress_bar.width(0); // Revert progress bar's width back to 0 for future uploads
    });
     
    multiple_photos_form.on('fileuploadprogressall', function (e, data) {
      bitrate.text((data.bitrate / 1024).toFixed(2) + 'Kb/s');
      var progress = parseInt(data.loaded / data.total * 100, 10);
      progress_bar.css('width', progress + '%').text(progress + '%');
    });

    $(document).bind('dragover', function (e) {
      var dropZone = $('#dropzone'),
              timeout = window.dropZoneTimeout;
      if (!timeout) {
        dropZone.addClass('in');
      } else {
        clearTimeout(timeout);
      }
      var found = false,
              node = e.target;
      do {
        if (node === dropZone[0]) {
          found = true;
          break;
        }
        node = node.parentNode;
      } while (node != null);
      if (found) {
        dropZone.addClass('hover');
      } else {
        dropZone.removeClass('hover');
      }
      window.dropZoneTimeout = setTimeout(function () {
        window.dropZoneTimeout = null;
        dropZone.removeClass('in hover');
      }, 100);
    });
  });